"""Standalone intake-form vision-extraction demo (W2 Task 13).

Reads an intake-form PDF off disk, runs it through the
``attach_and_extract`` pipeline configured with ``INTAKE_CONTRACT``,
and prints the validated ``IntakeFormExtraction`` to stdout. The
script intentionally short-circuits the JWT-validated
``get_document_bytes`` HTTP fetch — for the demo we read bytes
directly from a file path so you can point it at any sample PDF.
The full HTTP pipeline (fetch → render → extract → persist) plugs
into the orchestrator separately.

Run with:

    export ANTHROPIC_API_KEY=...
    cd sidecar

    # Default: extracts the bundled mock intake PDF
    uv run python scripts/intake_extraction_demo.py

    # Or point at any PDF on disk
    uv run python scripts/intake_extraction_demo.py /path/to/intake.pdf

The default PDF lives at ``data/samples/sample-intake.pdf``,
generated by ``scripts/generate_mock_intake.py``. Re-run that
script to see how the synthetic-but-realistic source data is
composed.

Optional flags:

    --document-id N   (default 1) — passed through to the extraction
    --patient-id N    (default 1) — passed through to the extraction
    --json            print the full IntakeFormExtraction as JSON
    --dpi N           render DPI (default 150)

Costs: one Anthropic vision call per invocation. Keep the PDF small;
this is a demo, not a benchmark.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

from agentforge.schemas.citation import PageBBox
from agentforge.tools.attach_and_extract import (
    DEFAULT_DPI,
    INTAKE_CONTRACT,
    PdfRenderer,
    VisionExtractor,
)


async def run(args: argparse.Namespace) -> int:
    pdf_path: Path = args.pdf.resolve()
    if not pdf_path.is_file():
        print(f"PDF not found: {pdf_path}", file=sys.stderr)
        return 2

    pdf_bytes = pdf_path.read_bytes()
    print(f"Loaded {len(pdf_bytes):,} bytes from {pdf_path.name}")

    renderer = PdfRenderer(dpi=args.dpi)
    pages = renderer.render_pages(pdf_bytes)
    page_summaries = ", ".join(
        f"p{p.page_number}={p.pixel_width}x{p.pixel_height}" for p in pages
    )
    print(f"Rendered {len(pages)} page(s): {page_summaries}")

    extractor = VisionExtractor(contract=INTAKE_CONTRACT)
    print("Calling Claude vision...")
    result = await extractor.extract(
        pages=pages,
        document_id=args.document_id,
        patient_id=args.patient_id,
    )

    extraction = result.extraction
    print()
    print("=" * 60)
    print("Intake-form extraction complete")
    print("=" * 60)
    print(f"  model:                {result.model}")
    print(f"  input_tokens:         {result.input_tokens:,}")
    print(f"  output_tokens:        {result.output_tokens:,}")
    print(f"  document_id:          {extraction.document_id}")
    print(f"  patient_id:           {extraction.patient_id}")
    print(f"  extraction_confidence:{extraction.extraction_confidence}")

    if extraction.chief_concern:
        cite = extraction.chief_concern_citation
        print(f"  chief_concern: {extraction.chief_concern!r}")
        if cite is not None and cite.page_bbox is not None:
            bbox = cite.page_bbox
            print(
                f"    citation: page={bbox.page} "
                f"({bbox.x0:.2f},{bbox.y0:.2f})-({bbox.x1:.2f},{bbox.y1:.2f}) "
                f"conf={bbox.bbox_confidence:.2f}"
            )
    else:
        print("  chief_concern: (none extracted)")

    print(f"  demographics: {len(extraction.demographics)} entries")
    for i, d in enumerate(extraction.demographics, start=1):
        print(f"    [{i}] {d.field}: {d.value!r}")
        _print_bbox_line(d.citation.page_bbox, indent=8)

    print(f"  medications: {len(extraction.medications)} entries")
    for i, m in enumerate(extraction.medications, start=1):
        dose = f" {m.dose}" if m.dose else ""
        freq = f" ({m.frequency})" if m.frequency else ""
        print(f"    [{i}] {m.name}{dose}{freq}")
        _print_bbox_line(m.citation.page_bbox, indent=8)

    print(f"  allergies: {len(extraction.allergies)} entries")
    for i, a in enumerate(extraction.allergies, start=1):
        rxn = f" — {a.reaction}" if a.reaction else ""
        sev = f" ({a.severity})" if a.severity else ""
        print(f"    [{i}] {a.substance}{rxn}{sev}")
        _print_bbox_line(a.citation.page_bbox, indent=8)

    print(f"  family_history: {len(extraction.family_history)} entries")
    for i, f in enumerate(extraction.family_history, start=1):
        print(f"    [{i}] {f.relative}: {f.condition}")
        _print_bbox_line(f.citation.page_bbox, indent=8)

    if extraction.unsupported_fields:
        print(f"  unsupported_fields ({len(extraction.unsupported_fields)}):")
        for f_name in extraction.unsupported_fields:
            print(f"    - {f_name}")

    if args.json:
        print()
        print("=" * 60)
        print("Full extraction JSON")
        print("=" * 60)
        print(json.dumps(extraction.model_dump(mode="json"), indent=2, default=str))

    return 0


def _print_bbox_line(bbox: PageBBox | None, indent: int) -> None:
    """Render a citation's page_bbox in a compact one-liner."""
    pad = " " * indent
    if bbox is None:
        print(f"{pad}(no bbox)")
        return
    print(
        f"{pad}page={bbox.page} "
        f"({bbox.x0:.2f},{bbox.y0:.2f})-({bbox.x1:.2f},{bbox.y1:.2f}) "
        f"conf={bbox.bbox_confidence:.2f}"
    )


_DEFAULT_SAMPLE_PDF = (
    Path(__file__).resolve().parents[1] / "data" / "samples" / "sample-intake.pdf"
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "pdf",
        type=Path,
        nargs="?",
        default=_DEFAULT_SAMPLE_PDF,
        help=(
            f"Path to a patient intake-form PDF on disk. "
            f"Defaults to the bundled mock intake at {_DEFAULT_SAMPLE_PDF.name}."
        ),
    )
    parser.add_argument("--document-id", type=int, default=1)
    parser.add_argument("--patient-id", type=int, default=1)
    parser.add_argument(
        "--dpi",
        type=int,
        default=DEFAULT_DPI,
        help=f"Render DPI (default {DEFAULT_DPI}).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the full IntakeFormExtraction as JSON after the summary.",
    )
    args = parser.parse_args(argv)
    return asyncio.run(run(args))


if __name__ == "__main__":
    sys.exit(main())
