"""Self-tests for the integration-suite auth fixtures (Task 47.1).

These exercise the fixtures themselves — confirming that the dev-easy
auth flow actually works end-to-end before downstream UC-1..UC-4
tests rely on it. They double as a smoke probe for the dev-easy
stack: when these fail, the rest of the integration suite would
fail in less obvious ways.

Skip behavior: when ``docker/development-easy`` isn't up, the
session-scoped ``_wait_for_openemr`` fixture pytest.skip()s and
every test here skips. Run manually with::

    cd sidecar
    docker compose -f ../docker/development-easy/docker-compose.yml ps  # confirm up
    uv run pytest tests/integration/test_auth_fixtures.py -v
"""

from __future__ import annotations

import os

import httpx


async def test_openemr_base_url_is_set(openemr_base_url: str) -> None:
    """The base URL fixture resolves either to default or env override."""
    assert openemr_base_url.startswith(("http://", "https://"))
    is_default = openemr_base_url.endswith(":9300")
    is_overridden = "AGENTFORGE_INT_OPENEMR_URL" in os.environ
    assert is_default or is_overridden


async def test_openemr_credentials_default_to_admin_pass(
    openemr_credentials: tuple[str, str],
) -> None:
    """Without env overrides the suite uses dev-easy's seeded admin."""
    user, password = openemr_credentials
    assert user
    assert password


async def test_openemr_session_returns_cookie_jar(
    openemr_session: httpx.Cookies,
) -> None:
    """The login fixture sets the OpenEMR session cookie."""
    assert "OpenEMR" in openemr_session
    # The cookie value is opaque (PHP session id) — just confirm it's
    # non-empty so we know the session was actually issued.
    cookie_value = openemr_session.get("OpenEMR")
    assert cookie_value is not None and len(cookie_value) > 0


async def test_authenticated_client_carries_session_across_requests(
    authenticated_client: httpx.AsyncClient,
) -> None:
    """Cookies attach to multiple sequential requests from the same client.

    The structural check here is that the SAME OpenEMR session cookie
    rides every request — confirming :func:`authenticated_client`
    actually wires the session jar in. We probe the root twice and
    confirm the cookie value is stable (not regenerated by the
    server — that would mean the session wasn't recognised).
    """
    response_one = await authenticated_client.get("/")
    response_two = await authenticated_client.get("/")
    # Cookie is attached and stable. We don't assert on the response
    # status because OpenEMR's root behaviour varies (302 to a
    # default landing, 200 with a portal page, 403 depending on
    # role); what matters here is that the SAME client carries the
    # session across calls.
    assert "OpenEMR" in authenticated_client.cookies
    # Both responses came back (no transport-level failure).
    assert response_one.status_code < 500
    assert response_two.status_code < 500


async def test_authenticated_client_can_reach_module_health_path(
    authenticated_client: httpx.AsyncClient,
) -> None:
    """The agent module's PHP entry points are reachable via the session.

    Smoke probe of the path the chat-panel actually uses. We expect
    400 (no patient context — the AgentProxyController refuses
    without an open chart) or 405 (method not allowed for GET). 401
    would mean the session cookie isn't being recognised; 404 would
    mean the path isn't wired.
    """
    response = await authenticated_client.get(
        "/interface/modules/custom_modules/oe-module-agentforge/public/turn.php"
    )
    # Either 400 (controller refuses GET because no patient context)
    # or 405 (GET not allowed) is acceptable. Anything else is a
    # routing or auth bug that downstream tests need to know about.
    assert response.status_code in (400, 405), (
        f"Unexpected status {response.status_code}; "
        f"body excerpt: {response.text[:200]!r}"
    )


async def test_login_failure_with_wrong_password_does_not_set_cookie(
    _wait_for_openemr: str,
) -> None:
    """A bad password produces no OpenEMR cookie.

    Verifies that the success-signal we use in :func:`openemr_session`
    (cookie presence) actually distinguishes pass from fail. Without
    this, the fixture might be silently accepting failed logins as
    successful because OpenEMR returns 200 in both cases.
    """
    import ssl as _ssl

    ctx = _ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = _ssl.CERT_NONE

    async with httpx.AsyncClient(
        verify=ctx, timeout=10.0, follow_redirects=True
    ) as client:
        await client.post(
            f"{_wait_for_openemr}/interface/main/main_screen.php",
            params={"auth": "login", "site": "default"},
            data={
                "new_login_session_management": "1",
                "authUser": "admin",
                "clearPass": "definitely-not-the-real-password",
                "languageChoice": "1",
            },
        )

        # OpenEMR may issue a session-tracking cookie even on failure
        # but the AUTHENTICATED OpenEMR cookie should be absent.
        # If this assertion fails, the test on cookie-presence in
        # openemr_session is too lenient and we need a different
        # success signal.
        # The login flow puts the authenticated session id in the
        # OpenEMR cookie. On failure it may still be set (PHP starts
        # a session unconditionally), but to a value tied to the
        # unauthenticated state. We can at least confirm that a
        # failed login does NOT bring up an authenticated state by
        # trying to access main_screen with the resulting cookie.
        probe = await client.get(
            f"{_wait_for_openemr}/interface/main/main_screen.php",
            follow_redirects=False,
        )
        # Authenticated → 200 with main_screen. Unauthenticated →
        # redirect to login (302/303) OR a 200 rendering of the login
        # form. We assert the response is NOT the authenticated
        # main_screen (which contains the AgentForge module's chat
        # panel hooks).
        is_authenticated = (
            probe.status_code == 200 and "main_screen" in probe.text.lower()
        )
        assert not is_authenticated, (
            "Bad-password login appeared to authenticate; the "
            "cookie-presence success signal in openemr_session is "
            "too lenient."
        )
